#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 608
#define TITLE "PerfectWorld"
#define PLAYER_WIDTH 32
#define PLAYER_HEIGHT 48
#define PLAYER_MOVE_SPEED 5
#define BULLET_SHOOTING_TIMER 10
#define PLAYER_HEALTH 100
#define BULLET_WIDTH 32
#define BULLET_HEIGHT 32
#define BULLET_MOVE_SPEED 8
#define SIZE_SMALL 32
#define PLAYER_IMAGE_PATH "../res/images/hero.png"
#define BULLET_IMAGE_PATH "../res/images/fire.png"
#define BACKGROUND_IMAGE_PATH "../res/images/art.jpg"
#define GRASS_IMAGE_PATH "../res/images/SNOW.png"
#define WALL_IMAGE_PATH "../res/images/BRICKS.png"
#define TREE_IMAGE_PATH "../res/images/WATER.png"
#define FOUNTAIN_IMAGE_PATH "../res/images/BIGLEAVES.png"
#define MAP_TEX_PATH "../res/maptype/1.txt"
